# Generated by Django 4.2.6 on 2023-11-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NovelInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('ncode', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
                ('story', models.TextField()),
                ('biggenre', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('keyword', models.TextField()),
                ('length', models.PositiveIntegerField()),
            ],
        ),
    ]
